CREATE TABLE `USERS` (
	`USER_ID`	BIGINT	NOT NULL,
	`LOGIN_ID`	VARCHAR(255)	NOT NULL,
	`PASSWORD`	VARCHAR(255)	NOT NULL,
	`NICKNAME`	VARCHAR(255)	NOT NULL,
	`AGE`	INT	NOT NULL,
	`GENDER`	VARCHAR(255)	NOT NULL,
	`PROFILE_IMAGE`	VARCHAR(255)	NULL,
	`PURPOSE`	VARCHAR(255)	NULL,
	`IS_DELETED`	BOOLEAN	NULL,
	`ROLE`	VARCHAR(255)	NOT NULL,
	`DELETED_AT`	DATETIME	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `CAKE_STORES` (
	`STORE_ID`	BIGINT	NOT NULL,
	`PLACE_ID`	VARCHAR(255)	NULL,
	`STORE_NAME`	VARCHAR(255)	NOT NULL,
	`STORE_SCORE`	INT	NULL,
	`STORE_TIME`	VARCHAR(255)	NULL,
	`STORE_PHONE_NUMBER`	VARCHAR(255)	NULL,
	`STORE_INTRODUCE`	VARCHAR(255)	NULL,
	`LATITUDE`	DOUBLE	NOT NULL,
	`LONGITUDE`	DOUBLE	NOT NULL,
	`STORE_IMAGE`	VARCHAR(255)	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `LIKES` (
	`LIKE_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `HASHTAGS` (
	`HASHTAG_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `RESERVATIONS` (
	`RESERVATION_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`USER_CNT`	INT	NULL,
	`RESERVATION_DATE`	DATETIME	NOT NULL,
	`RESERVATION_IMAGE`	VARCHAR(255)	NULL,
	`RESERVATION_DETAIL`	VARCHAR(255)	NULL,
	`RESERVATION_CHECK`	VARCHAR(255)	NULL,
	`VERSION`	INT	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `REVIEWS` (
	`REVIEW_ID`	BIGINT	NOT NULL,
	`STORE_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`CONTENT`	VARCHAR(255)	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `NIC_ADJECTIVE` (
	`NICK_ADJ_ID`	BIGINT	NOT NULL,
	`WORD`	VARCHAR(255)	NULL
);

CREATE TABLE `UPLOAD_FILES` (
	`FILE_ID`	BIGINT	NOT NULL,
	`TITLE`	VARCHAR(255)	NULL,
	`S3_URL`	VARCHAR(255)	NOT NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

CREATE TABLE `NIC_CAKE` (
	`NICK_CAKE_ID`	BIGINT	NOT NULL,
	`WORD`	VARCHAR(255)	NULL
);

CREATE TABLE `CURATION` (
	`CURATION_ID`	BIGINT	NOT NULL,
	`USER_ID`	BIGINT	NOT NULL,
	`TITLE`	VARCHAR(255)	NOT NULL,
	`CONTENT`	VARCHAR(255)	NOT NULL,
	`IMAGE`	VARCHAR(255)	NULL,
	`CREATED_AT`	DATETIME	NOT NULL,
	`UPDATED_AT`	DATETIME	NULL
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `CAKE_STORES` ADD CONSTRAINT `PK_CAKE_STORES` PRIMARY KEY (
	`STORE_ID`
);

ALTER TABLE `LIKES` ADD CONSTRAINT `PK_LIKES` PRIMARY KEY (
	`LIKE_ID`
);

ALTER TABLE `HASHTAGS` ADD CONSTRAINT `PK_HASHTAGS` PRIMARY KEY (
	`HASHTAG_ID`
);

ALTER TABLE `RESERVATIONS` ADD CONSTRAINT `PK_RESERVATIONS` PRIMARY KEY (
	`RESERVATION_ID`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `PK_REVIEWS` PRIMARY KEY (
	`REVIEW_ID`
);

ALTER TABLE `NIC_ADJECTIVE` ADD CONSTRAINT `PK_NIC_ADJECTIVE` PRIMARY KEY (
	`NICK_ADJ_ID`
);

ALTER TABLE `UPLOAD_FILES` ADD CONSTRAINT `PK_UPLOAD_FILES` PRIMARY KEY (
	`FILE_ID`
);

ALTER TABLE `NIC_CAKE` ADD CONSTRAINT `PK_NIC_CAKE` PRIMARY KEY (
	`NICK_CAKE_ID`
);

ALTER TABLE `CURATION` ADD CONSTRAINT `PK_CURATION` PRIMARY KEY (
	`CURATION_ID`
);

